# Generated by Django 5.2.17 on 2026-10-06 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('lan_domain', models.CharField(default='intranet.example.tld', max_length=253)),
                ('vpn_domain', models.CharField(default='vpn.example.tld', max_length=253)),
                ('lan_prefix', models.CharField(default='192.168', max_length=7)),
                ('vpn_prefix', models.CharField(default='172.28', max_length=7)),
                ('gandi_zone', models.CharField(default='example.tld', max_length=253)),
                ('gandi_token', models.CharField(blank=True, default='', max_length=512)),
                ('ttl', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('soa_ns', models.CharField(default='ns.intranet.example.tld', max_length=253)),
                ('soa_mailbox', models.CharField(default='hostmaster.intranet.example.tld', max_length=253)),
                ('revision', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='configuration_singleton'), models.CheckConstraint(condition=models.Q(('revision__gte', 1), ('revision__lte', 4294967295)), name='configuration_serial_bounds'), models.CheckConstraint(condition=models.Q(('ttl__gte', 1), ('ttl__lte', 4294967295)), name='configuration_ttl_bounds')],
            },
        ),
        migrations.CreateModel(
            name='GandiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=253)),
                ('name', models.CharField(max_length=253)),
                ('record_type', models.CharField(choices=[('A', 'A')], default='A', max_length=1)),
                ('values', models.JSONField(default=list)),
                ('ttl', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('zone', 'name', 'record_type'), name='gandi_unique_owned_record'), models.CheckConstraint(condition=models.Q(('record_type', 'A')), name='gandi_record_type'), models.CheckConstraint(condition=models.Q(('ttl__gte', 1), ('ttl__lte', 4294967295)), name='gandi_ttl_bounds')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('g', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('id__gte', 1), ('id__lte', 4)), name='site_fixed_ids'), models.CheckConstraint(condition=models.Q(('g__lte', 255)), name='site_octet_bounds')],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('row', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('running', 'Running'), ('decommissioned', 'Decommissioned'), ('unconfirmed', 'Unconfirmed')], default='running', max_length=14)),
                ('vpn', models.BooleanField(default=False)),
                ('public_export', models.BooleanField(default=False)),
                ('mac', models.CharField(blank=True, default='', max_length=17)),
                ('notes', models.TextField(blank=True, default='', max_length=4000)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='inventory.site')),
            ],
            options={
                'ordering': ['column', 'row'],
                'constraints': [models.UniqueConstraint(fields=('row', 'column'), name='host_unique_position'), models.UniqueConstraint(condition=models.Q(('mac', ''), _negated=True), fields=('mac',), name='host_unique_nonempty_mac'), models.CheckConstraint(condition=models.Q(('row__lte', 15)), name='host_row_bounds'), models.CheckConstraint(condition=models.Q(('column__lte', 7)), name='host_column_bounds'), models.CheckConstraint(condition=models.Q(('column', 0), ('row', 0), _negated=True), name='host_reserved_position'), models.CheckConstraint(condition=models.Q(('status__in', ['running', 'decommissioned', 'unconfirmed'])), name='host_status_choices')],
            },
        ),
    ]
