# Generated by Django 5.2.17 on 2026-10-06 03:55

from django.db import migrations


def seed_inventory(apps, schema_editor):
    configuration = apps.get_model("inventory", "Configuration")
    site = apps.get_model("inventory", "Site")
    database = schema_editor.connection.alias
    configuration.objects.using(database).get_or_create(
        pk=1, defaults={"soa_ns": "ns.example.tld"}
    )
    for number in range(1, 5):
        site.objects.using(database).get_or_create(
            pk=number, defaults={"name": f"Site{number}", "g": number}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_inventory, migrations.RunPython.noop),
    ]
