# Generated by Django 5.2.17 on 2026-10-06 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=4000, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
