# Generated by Django 5.2.17 on 2026-10-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_enforce_notes_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='soa_ns',
            field=models.CharField(default='ns.example.tld', max_length=253),
        ),
    ]
