# Generated by Django 5.2.17 on 2026-10-06 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_external_default_soa_ns'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dsm_ifname',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9_.-]+\\Z', 'Enter a DSM interface name such as ovs_eth0.')]),
        ),
    ]
