# Generated by Django 5.2.17 on 2026-10-08 04:45

import django.core.validators
from django.db import migrations, models


def preserve_soa_settings(apps, schema_editor):
    Configuration = apps.get_model('inventory', 'Configuration')
    for config in Configuration.objects.using(schema_editor.connection.alias).all():
        Configuration.objects.using(schema_editor.connection.alias).filter(pk=config.pk).update(
            zone_ns=config.soa_ns, soa_refresh=3600, soa_retry=900,
            soa_minimum=min(config.ttl, 300),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_site_dsm_ifname'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='dns_export_directory',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='configuration',
            name='soa_expire',
            field=models.PositiveIntegerField(default=1209600, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='soa_minimum',
            field=models.PositiveIntegerField(default=10800, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='soa_refresh',
            field=models.PositiveIntegerField(default=43200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='soa_retry',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='zone_ns',
            field=models.CharField(default='ns.example.tld', max_length=253),
        ),
        migrations.RunPython(preserve_soa_settings, migrations.RunPython.noop),
    ]
