# Generated by Django 5.2.17 on 2026-10-08 13:06

import django.core.validators
import inventory.dns_serial
from django.db import migrations, models


def preserve_serial(apps, schema_editor):
    configuration = apps.get_model("inventory", "Configuration")
    for config in configuration.objects.using(schema_editor.connection.alias).all():
        # Preserve even incompatible high legacy values. Publication explicitly
        # rejects them with reset guidance rather than silently lowering them.
        configuration.objects.using(schema_editor.connection.alias).filter(pk=config.pk).update(
            soa_serial=max(config.revision, inventory.dns_serial.initial_serial()),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_configuration_dns_export_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='dns_content_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='configuration',
            name='dns_nas_host',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.AddField(
            model_name='configuration',
            name='dns_nas_port',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='dns_nas_user',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='configuration',
            name='dns_published_generation',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='configuration',
            name='soa_serial',
            field=models.PositiveBigIntegerField(default=inventory.dns_serial.initial_serial, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.RunPython(preserve_serial, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.CheckConstraint(condition=models.Q(('soa_serial__gte', 1), ('soa_serial__lte', 4294967295)), name='configuration_dns_serial_bounds'),
        ),
    ]
